name: Bandit Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      checks: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Create virtual environment
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        python -m venv .venv

    - name: Install dependencies
      run: |
        source .venv/bin/activate
        if [ -f pyproject.toml ]; then
          uv pip install -e ".[dev]"
        fi

    - name: Install Bandit
      run: |
        source .venv/bin/activate
        python -m pip install bandit[toml,sarif]
        
    - name: Run Bandit Security Scan
      run: |
        source .venv/bin/activate
        bandit -c pyproject.toml -r trustyai/ -f sarif -o results.sarif
      continue-on-error: true
      
    - name: Upload SARIF results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif
        category: bandit-security-scan
      continue-on-error: true
      
    - name: Upload SARIF as artifact
      uses: actions/upload-artifact@v4
      with:
        name: bandit-sarif-results
        path: results.sarif
        retention-days: 30
      continue-on-error: true 